### PR TITLE
fix: fix race conditions when closing and destroying streams

### LINKED ISSUE #55: Race condition when closing `writableFromUser`
Our React app uses `@apollo/client-react-streaming` along with `injectToStream()` to inject Apollo context into the render stream. We've noticed that when dumping large (100k+) Apollo responses to the stream, we were getting `premature stream close` errors that left the page in a broken state where the server response was cut off abruptly. This didn't seem to happen with smaller injections.

We narrowed it down to [`writableFromUser.end()` being called](https://github.com/brillout/react-streaming/blob/main/src/server/renderToStream/createPipeWrapper.ts#L60) immediately before `onEnded()` and `callback()`. Calling these two callbacks in the callback function for `writableFromUser.end()` seems to fix it for us, as well as skipping the [`writableFromUser.destroy()` call below it](https://github.com/brillout/react-streaming/blob/main/src/server/renderToStream/createPipeWrapper.ts#L69) if `!writableFromUser.writableEnded`. Not sure if this is the most correct fix, though.

### PR DESCRIPTION
**Pull request by karmeleon**
Fixes #55

When injecting a large amount of data right at the end of a streaming render, it's important to make sure that the streams have all their data fully flushed through before cleaning them up. We've been using this patch in production for nearly a year and it's fully solved our `ERR_STREAM_PREMATURE_CLOSE` issues.

### CODE REVIEW

File: src/server/renderToStream/createPipeWrapper.ts [hunk 1]
```diff
@@ -57,16 +57,21 @@ async function createPipeWrapper(
           debug('final')
           clearTimeouts()
           await onBeforeEnd()
-          writableFromUser.end()
-          onEnded()
-          callback()
+          writableFromUser.end(() => {
```
Comment (brillout) [inline src/server/renderToStream/createPipeWrapper.ts:61]:
```suggestion
          // https://github.com/brillout/react-streaming/pull/56
          writableFromUser.end(() => {
```

**Comment by brillout** [comment]
Released in `0.4.17` — thank you for your PR :green_heart:
